---
- name: Install required packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: yes
  become: yes

- name: Add Sury's APT key
  apt_key: 
    url: "{{ php_key_url }}"
    state: present

- name: Add Sury repository
  ansible.builtin.apt_repository:
    repo: "deb {{ php_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  become: yes 

- name: Install php
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes
  become: yes
