---
- name: update
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: 
      - lsb-release
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: Add PHP repository
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: Installation des paquets PHP
  apt:
    name:
      - php7.4
      - openssl
      - php-common
      - php-curl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
    state: present
