version: "3.7"

services:
  infra:
    build: 
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/ansible
    volumes: 
      - ./ansible:/root/ansible
    command: tail -f /dev/null