---
- name: Create project directory and set its permissions
  file:
    path: "/root/var/www/back"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes