---
- name: Check if MySQL is already installed.
  ansible.builtin.stat:
    path: "/etc/mysql/my.cnf"
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  ansible.builtin.apt:
    update_cache: yes
  changed_when: False
  when: not mysql_installed.stat.exists

- name: Ensure MySQL packages are installed.
  ansible.builtin.apt:
    name: "default-mysql-server"
    state: present
    policy_rc_d: 101
  register: deb_mysql_install_packages

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MySQL is stopped after initial install.
  ansible.builtin.service:
    name: "mariadb"
    state: stopped
  when: not mysql_installed.stat.exists