---
- name: Create project directory and set its permissions
  file:
    path: "/root/var/www/front"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: install rsync
  package:
    name: rsync
    state: present