- name: delete temp directory
  file:
    state: absent
    path: "~/var/www/temp"
    
- name: recreate temp directory
  file:
    state: directory
    path: "~/var/www/temp"

- name: copy project
  ansible.builtin.copy:
    src: /builds/d4v1dh/test/app/back/
    dest: ~/var/www/temp