- name: delete temp directory
  file:
    state: absent
    path: "~/var/www/temp"
    
- name: recreate temp directory
  file:
    state: directory
    path: "~/var/www/temp"

- name: copy project
  ansible.builtin.copy:
    src: ~/code/T-NSA/temp/back/
    dest: ~/var/www/temp
          
- name: stop nginx server
  service: name=nginx state=stopped enabled=no

- name: deleting prod directory
  file:
    state: absent
    path: "~/var/www/back"

- name: recreating prod directory
  file:
    state: directory
    path: "~/var/www/back"
    
- name: put project in prod directory
  ansible.builtin.copy:
    src: ~/var/www/temp/ 
    dest: ~/var/www/back
    remote_src: yes

- name: Create .env file
  template:
    src: .env
    dest: /var/www/back
    owner: "{{ ansible_user }}"
    group: "{{ ansible_password }}"
    mode: 0644

- name: clear laravel
  shell: |
    cd /root/var/www/back
    php artisan config:cache
    php artisan cache:clear
    php artisan optimize:clear

- name: apply migrations
  command: php /var/www/back/artisan migrate

- name: restart nginx server
  service: 
    name: nginx 
    state: restarted