---
- hosts: backend
  become: true

  roles:
    - env_back
    - nginx_back
    - php
    - composer

- hosts: database

  roles:
    - role: mysql
      become: yes

- hosts: frontend

  roles:
    - env_front
    - nginx_front
    - node
    - angular
